# -*- coding: utf-8 -*-
"""정승윤_가설 검정의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O83i7GvpdE2bD1VAQIkvpQClkEqM5HW2
"""

# 폰트 설정
# !sudo apt-get install -y fonts-nanum
# !sudo fc-cache -fv
# !rm -rf ~/.cache/matplotlib

# === 기본 라이브러리 ===
import os
import warnings
from contextlib import contextmanager
from time import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

# === 머신러닝 ===
import lightgbm as lgbm
from scipy import stats
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression,HuberRegressor
from scipy.stats import spearmanr,mannwhitneyu
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import (
    mean_squared_error, mean_absolute_error, r2_score,
    classification_report, confusion_matrix,
    accuracy_score, f1_score, roc_auc_score,
)

# === 시각화 한글/스타일 설정 ===
warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid')

# 2. 위에서 출력된 폰트 이름 중 하나를 여기에 정확히 적어주세요!
font_family = 'NanumBarunGothic'

# 3. 맷플롯립과 시본에 강제로 고정
plt.rc('font', family=font_family)
sns.set_theme(style='whitegrid', font=font_family)
plt.rcParams['axes.unicode_minus'] = False

print(f"🔥 {font_family} 폰트로 강제 고정 완료!")

from google.colab import drive

# 1. 구글 드라이브 마운트
drive.mount('/content/drive')

# === 데이터 경로 ===
# 같은 폴더에 data/ 가 있을 수도, 루트에 바로 있을 수도 있음 → 자동 탐색

drive.mount('/content/drive')

# 2. 경로 설정: '9냥해' 폴더 안의 '데이터 셋' 폴더를 타겟으로 합니다.
CANDIDATE_DIRS = [
    '/content/drive/MyDrive/9냥해/1. 데이터 셋',
    '/content/drive/MyDrive/9냥해',
    './data',
    '.'
]

def find_csv(filename: str) -> str:
    for d in CANDIDATE_DIRS:
        p = os.path.join(d, filename)
        if os.path.exists(p):
            return p
    raise FileNotFoundError(f"'{filename}'을(를) 찾을 수 없습니다. '9냥해' 내 폴더명을 확인하세요.")

# 파일 찾기 및 로드
try:
    MAIN = find_csv('Combined_data.csv')
    CSV = find_csv('True_Stability_Rheology_Data.csv')

    print('csv dataset 발견:', MAIN)
    print('csv dataset 발견:', CSV)

    # 데이터 읽기
    df = pd.read_csv(MAIN)
    df_csv = pd.read_csv(CSV)


    print("\n[성공] 모든 데이터를 정상적으로 불러왔습니다!")

except FileNotFoundError as e:
    print(f"[오류] {e}")

# 정수형인 ID를 문자열로 변경
df['ID'] = df['ID'].astype(str)

# 점도 추출 파생변수

import ast

# Rheology_Data에서 첫 번째 점도값만 추출하는 함수
def get_first_viscosity(rheo_str):
    if pd.isna(rheo_str):
        return np.nan
    try:
        # 문자열 데이터를 파이썬 리스트/딕셔너리 형태로 변환
        data = ast.literal_eval(rheo_str)
        # avg_viscosity 리스트의 0번째(첫 번째) 값을 가져옴
        return data[1]['avg_viscosity'][0]
    except (ValueError, IndexError, TypeError):
        return np.nan

# 새로운 파생변수 'Initial_Viscosity' 생성
df['Initial_Viscosity'] = df['Rheology_Data'].apply(get_first_viscosity)
df['Initial_Viscosity'] = pd.to_numeric(df['Initial_Viscosity'], errors='coerce')

# 데이터 확인 (생성된 첫 5개 행 확인)
print(df[['Initial_Viscosity', 'Turbidity_NTU']].head())

# 안정성 결과가 True인 데이터만 추출하여 df_true 생성
df_true = df[df['Stability_Test'] == True].copy()

# 총 전하별 탄소 비율 파생변수 생성 (백분율 * 100 반영)
total_c = df_true["TOTAL_derived"] + 1e-5

# 1. 중성 탄소 비율 (%)
df_true['C_0_Ratio'] = (df_true['C_0_derived'] / total_c) * 100

# 2. 음전하 탄소 8개 전체 합 및 비율 (%)
neg_cols = [f'C_neg{i}_derived' for i in range(1, 9)]
df_true['C_neg_Total_Ratio'] = (df_true[neg_cols].sum(axis=1) / total_c) * 100

# 3. 양전하 탄소 6개 전체 합 및 비율 (%)
pos_cols = [f'C_pos{i}_derived' for i in range(1, 7)]
df_true['C_pos_Total_Ratio'] = (df_true[pos_cols].sum(axis=1) / total_c) * 100


# 최종 서치 및 학습 모델에 주입할 파생변수 피처 리스트 정의
ratio_features = ['C_0_Ratio', 'C_neg_Total_Ratio', 'C_pos_Total_Ratio']

print("--- 생성된 전하별 총 비율(_Ratio) 파생 변수 이름 목록 ---")
print(ratio_features)

df_clean = df[(df['Initial_Viscosity'] >= 0) & (df['Initial_Viscosity'] < 25000)].copy()

"""# **점도**

##**분포**
"""

# 보통 등급에 점도가 1인 데이터 확인
import ast

# 1. 조건 필터링
target_data = df[(df['Viscosity'] == 'MEDIUM') & (df['Initial_Viscosity'] <= 100)]

# 2. 결과 출력
if not target_data.empty:
    print(f"조건에 맞는 데이터 개수: {len(target_data)}개\n")
    print("-" * 50)

    for index, row in target_data.iterrows():
        print(f"ID: {row['ID']}")

        try:
            # 문자열을 리스트/딕셔너리 구조로 변환
            rheo_list = ast.literal_eval(row['Rheology_Data'])

            # 리스트 안에서 'avg_viscosity' 키를 가진 딕셔너리 찾기
            found = False
            for item in rheo_list:
                if isinstance(item, dict) and 'avg_viscosity' in item:
                    print(f"avg_viscosity 값: {item['avg_viscosity']}")
                    found = True
                    break
            if not found:
                print("avg_viscosity 데이터를 찾을 수 없습니다.")
        except Exception as e:
            print(f"데이터 파싱 오류: {e}")

        print("-" * 50)
else:
    print("조건에 맞는 데이터가 없습니다.")

"""#**가설2**

"""

targets = ['Dehyton ML', 'Dehyton MC', 'Dehyton PK 45', 'Dehyton AB 30',
           'Texapon SB 3 KC', 'Plantapon ACG 50', 'Plantapon LC 7', 'Plantapon Amino SCG-L', 'Plantapon Amino KG-L',
           'Plantacare 818', 'Plantacare 2000',
           'Dehyquart A-CA',
           'Salcare Super 7', 'Dehyquart CC6', 'Dehyquart CC7 Benz', 'Luviquat Excellence',
           'Arlypon TT','Arlypon F']

target_df = df_clean[
    (df_clean['Initial_Viscosity'] >= 100) &
    (df_clean['Initial_Viscosity'] <= 5000) &
    (df_clean['Turbidity_NTU'] <= 100)
].copy()

replaced = target_df[targets].replace(0, np.nan)

# 2. 통계량 계산
summary_stats_filtered = replaced.agg(['mean', 'min', 'max']).T

# 3. 결과 출력
print("--- 목표 조건(성공 제품)을 만족하는 성분별 통계 ---")
print(summary_stats_filtered.round(2))

import pandas as pd
import numpy as np

# 1. 목표 조건 적용 및 데이터 전처리
target_df = df_clean[
    (df_clean['Initial_Viscosity'] >= 100) &
    (df_clean['Initial_Viscosity'] <= 5000) &
    (df_clean['Turbidity_NTU'] <= 100)
].copy()

# 2. 성분 리스트 설정
surfactants = ['Dehyton ML', 'Dehyton MC', 'Dehyton PK 45', 'Dehyton AB 30',
               'Texapon SB 3 KC', 'Plantapon ACG 50', 'Plantapon LC 7', 'Plantapon Amino SCG-L',
               'Plantapon Amino KG-L', 'Plantacare 818', 'Plantacare 2000', 'Dehyquart A-CA']
polymers = ['Salcare Super 7', 'Dehyquart CC6', 'Dehyquart CC7 Benz', 'Luviquat Excellence']

# 3. 조합(Combination) 생성 함수
def get_combination(row):
    active_surfs = [s for s in surfactants if row.get(s, 0) > 0]
    return tuple(sorted(active_surfs))

# 4. 데이터에 조합 정보 추가
df_analysis = target_df.copy()
df_analysis['Surfactant_Combo'] = df_analysis.apply(get_combination, axis=1)

# 5. 폴리머 통계 계산 (조합별, 0은 NaN 처리)
df_analysis[polymers] = df_analysis[polymers].replace(0, np.nan)
combo_polymer_stats = df_analysis.groupby('Surfactant_Combo')[polymers].agg(['mean', 'min', 'max'])

# 6. 계면활성제 상세 함량 범위 분석 (조합별, 각 성분별)
combo_counts = df_analysis['Surfactant_Combo'].value_counts()
summary_list = []

for combo in combo_counts.index:
    mask = df_analysis['Surfactant_Combo'] == combo
    subset = df_analysis.loc[mask, surfactants]
    stats = subset.replace(0, np.nan).agg(['min', 'max']).T.dropna(how='all')
    stats['Combo'] = str(combo)
    stats['Count'] = combo_counts[combo]
    summary_list.append(stats)

final_df = pd.concat(summary_list)
final_df = final_df.reset_index().rename(columns={'index': 'Ingredient'})

# --- 결과 출력 ---
print("=== [분석 1] 계면활성제 조합별 폴리머 사용 통계 ===")
print(combo_polymer_stats.stack(level=0).sort_index())

print("\n=== [분석 2] 계면활성제 조합별 각 성분의 상세 사용 범위 (Min - Max) ===")
# 조합별, 빈도별로 그룹화하여 출력
print(final_df.groupby(['Combo', 'Count', 'Ingredient'])[['min', 'max']].first().sort_index(level='Count', ascending=False))

print("\n=== [분석 3] 상위 5개 빈도 조합 ===")
print(df_analysis['Surfactant_Combo'].value_counts().head(5))

import pandas as pd
import numpy as np

# 1. 데이터 필터링 (성공 제형만 추출)
target_df = df_clean[
    (df_clean['Initial_Viscosity'] >= 100) &
    (df_clean['Initial_Viscosity'] <= 5000) &
    (df_clean['Turbidity_NTU'] <= 100)
].copy()

# 2. 성분 및 증점제 리스트 설정
surfactants = ['Dehyton ML', 'Dehyton MC', 'Dehyton PK 45', 'Dehyton AB 30',
               'Texapon SB 3 KC', 'Plantapon ACG 50', 'Plantapon LC 7', 'Plantapon Amino SCG-L',
               'Plantapon Amino KG-L', 'Plantacare 818', 'Plantacare 2000', 'Dehyquart A-CA']

# Arlypon 계열을 포함한 증점제 리스트
polymers = ['Arlypon TT', 'Arlypon F']

# 3. 계면활성제 조합 생성
def get_combination(row):
    active_surfs = [s for s in surfactants if row.get(s, 0) > 0]
    return tuple(sorted(active_surfs))

df_analysis = target_df.copy()
df_analysis['Surfactant_Combo'] = df_analysis.apply(get_combination, axis=1)

# 4. 폴리머 함량 통계 계산 준비
df_analysis[polymers] = df_analysis[polymers].replace(0, np.nan)

# 데이터를 길게(melt) 변환하여 조합-폴리머-함량 구조로 만듦
df_melted = df_analysis.melt(
    id_vars=['Surfactant_Combo'],
    value_vars=polymers,
    var_name='Polymer',
    value_name='Concentration'
)

# 증점제가 사용된(NaN이 아닌) 경우만 필터링
df_melted = df_melted.dropna(subset=['Concentration'])

# 5. 조합별 + 폴리머별 통계량(평균, 최소, 최대, 빈도) 계산
polymer_stats = df_melted.groupby(['Surfactant_Combo', 'Polymer'])['Concentration'].agg(['mean', 'min', 'max', 'count'])

# 6. 해당 계면활성제 조합의 전체 빈도수 결합
combo_counts = df_analysis['Surfactant_Combo'].value_counts().rename('Combo_Frequency')
final_report = polymer_stats.join(combo_counts, on='Surfactant_Combo')

# --- 결과 출력 ---
print("=== [분석] 계면활성제 조합별 사용된 증점제 종류 및 사용량 상세 통계 ===")
# 전체 빈도수와 조합 기준으로 정렬하여 출력
print(final_report.sort_values(by=['Combo_Frequency', 'Surfactant_Combo'], ascending=[False, True]).round(2))

# 엑셀 저장용 (필요시 주석 해제)
# final_report.to_csv('Surfactant_Polymer_Analysis.csv', encoding='utf-8-sig')