# -*- coding: utf-8 -*-
"""점도등급 분류 모델

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z363VlZJOM_U7AcBRSUvyFkx-Di6qv9J
"""

# 폰트 설정
# !sudo apt-get install -y fonts-nanum
# !sudo fc-cache -fv
# !rm ~/.cache/matplotlib -rf

# === 기본 라이브러리 ===
import os
import warnings
from contextlib import contextmanager
from time import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

# === 머신러닝 ===
import lightgbm as lgbm
from scipy import stats
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_squared_error, mean_absolute_error, r2_score,
    classification_report, confusion_matrix,
    accuracy_score, f1_score, roc_auc_score,
)

# === 시각화 한글/스타일 설정 ===
warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid')

# 2. 위에서 출력된 폰트 이름 중 하나를 여기에 정확히 적어주세요!
font_family = 'NanumBarunGothic'

# 3. 맷플롯립과 시본에 강제로 고정
plt.rc('font', family=font_family)
sns.set_theme(style='whitegrid', font=font_family)
plt.rcParams['axes.unicode_minus'] = False

print(f"🔥 {font_family} 폰트로 강제 고정 완료!")

from google.colab import drive

# 1. 구글 드라이브 마운트
drive.mount('/content/drive')

# === 데이터 경로 ===
# 같은 폴더에 data/ 가 있을 수도, 루트에 바로 있을 수도 있음 → 자동 탐색

drive.mount('/content/drive')

# 2. 경로 설정: '9냥해' 폴더 안의 '데이터 셋' 폴더를 타겟으로 합니다.
CANDIDATE_DIRS = [
    '/content/drive/MyDrive/9냥해/1. 데이터 셋',
    '/content/drive/MyDrive/9냥해',
    './data',
    '.'
]

def find_csv(filename: str) -> str:
    for d in CANDIDATE_DIRS:
        p = os.path.join(d, filename)
        if os.path.exists(p):
            return p
    raise FileNotFoundError(f"'{filename}'을(를) 찾을 수 없습니다. '9냥해' 내 폴더명을 확인하세요.")

# 파일 찾기 및 로드
try:
    MAIN = find_csv('Combined_data.csv')
    CSV = find_csv('True_Stability_Rheology_Data.csv')

    print('csv dataset 발견:', MAIN)
    print('csv dataset 발견:', CSV)

    # 데이터 읽기
    df = pd.read_csv(MAIN)
    df_csv = pd.read_csv(CSV)


    print("\n[성공] 모든 데이터를 정상적으로 불러왔습니다!")

except FileNotFoundError as e:
    print(f"[오류] {e}")

# 정수형인 ID를 문자열로 변경
df['ID'] = df['ID'].astype(str)

# 안정성 결과가 True인 데이터만 추출하여 df_true 생성
df_true = df[df['Stability_Test'] == True].copy()

# 점도 추출 파생변수

import ast

# Rheology_Data에서 첫 번째 점도값만 추출하는 함수
def get_first_viscosity(rheo_str):
    if pd.isna(rheo_str):
        return np.nan
    try:
        # 문자열 데이터를 파이썬 리스트/딕셔너리 형태로 변환
        data = ast.literal_eval(rheo_str)
        # avg_viscosity 리스트의 0번째(첫 번째) 값을 가져옴
        return data[1]['avg_viscosity'][0]
    except (ValueError, IndexError, TypeError):
        return np.nan

# 새로운 파생변수 'Initial_Viscosity' 생성
df['Initial_Viscosity'] = df['Rheology_Data'].apply(get_first_viscosity)
df['Initial_Viscosity'] = pd.to_numeric(df['Initial_Viscosity'], errors='coerce')

# 데이터 확인 (생성된 첫 5개 행 확인)
print(df[['Initial_Viscosity', 'Turbidity_NTU']].head())

df.info()

df.head()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. 한글 폰트 및 스타일 설정
plt.rcParams['font.family'] = 'NanumBarunGothic'  # 또는 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False
sns.set_theme(style="whitegrid", font='NanumGothic')

# 2. 영문 등급 -> 한글 변환 맵 정의
viscosity_map = {
    'VERY-LOW': '매우 낮음',
    'LOW': '낮음',
    'MEDIUM': '보통',
    'HIGH': '높음'
}

df_plot = df_true.copy()
df_plot['Viscosity_Ko'] = df_plot['Viscosity'].map(viscosity_map)

# 3. 결측치(NaN) 제거
df_plot = df_plot.dropna(subset=['Viscosity_Ko'])

# 4. 그래프 크기 및 순서 정의
plt.figure(figsize=(8, 5))
viscosity_order_ko = ['매우 낮음', '낮음', '보통', '높음']

# 5. 카운트 플롯 그리기
ax = sns.countplot(
    data=df_plot,
    x='Viscosity_Ko',
    order=viscosity_order_ko,
    palette="Blues_r"
)

# 🔥 [핵심 수정] 버전 최적화: 생성된 모든 막대 묶음(Container)을 돌면서 숫자를 붙여줍니다.
for container in ax.containers:
    ax.bar_label(container, fmt='%d', fontsize=11, fontweight='bold', padding=3)

# 6. 타이틀 및 레이블 디자인 정돈
plt.title("점도 등급별 분포", fontsize=14, pad=15, fontweight='bold')
plt.xlabel(" ", fontsize=11, labelpad=10)
plt.ylabel("개수", fontsize=11, labelpad=10)

# 7. 레이아웃 조절 및 저장
plt.tight_layout()
plt.savefig("점도_등급별_분포.png", dpi=300, bbox_inches='tight')
plt.show()

# 총 전하별 탄소 비율 파생변수 생성 (백분율 * 100 반영)
total_c = df_true["TOTAL_derived"] + 1e-5

# 1. 중성 탄소 비율 (%)
df_true['C_0_Ratio'] = (df_true['C_0_derived'] / total_c) * 100

# 2. 음전하 탄소 8개 전체 합 및 비율 (%)
neg_cols = [f'C_neg{i}_derived' for i in range(1, 9)]
df_true['C_neg_Total_Ratio'] = (df_true[neg_cols].sum(axis=1) / total_c) * 100

# 3. 양전하 탄소 6개 전체 합 및 비율 (%)
pos_cols = [f'C_pos{i}_derived' for i in range(1, 7)]
df_true['C_pos_Total_Ratio'] = (df_true[pos_cols].sum(axis=1) / total_c) * 100


# 최종 서치 및 학습 모델에 주입할 파생변수 피처 리스트 정의
ratio_features = ['C_0_Ratio', 'C_neg_Total_Ratio', 'C_pos_Total_Ratio']

print("--- 생성된 전하별 총 비율(_Ratio) 파생 변수 이름 목록 ---")
print(ratio_features)

import pandas as pd
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor


refined_features = [
    'Arlypon TT',  'Arlypon F', # 증점제
    'Luviquat Excellence', 'Dehyquart CC6', 'Dehyquart CC7 Benz', 'Salcare Super 7', # 폴리머
    'C[N+](C)(C)C_derived','CS(=O)(=O)[O-]_derived','CC(=O)[O-]_derived','[H]C(C)(OC)OC_derived', # 작용기 및 극성 구조
    'C_0_Ratio',           # 중성 탄소수 총 비율 (%)
    'C_neg_Total_Ratio',   # 음전하 탄소 총 비율 (%)
    'C_pos_Total_Ratio'    # 양이온 탄소수 총 비율 (%)
]
# refined_features = [
#                     'Arlypon TT',
#                     'Dehyton PK 45', 'Texapon SB 3 KC','Plantacare 818', 'Plantapon Amino SCG-L', 'Plantapon ACG 50', 'Plantapon LC 7',
#                     'Luviquat Excellence',
#                     'C_0_Ratio','C_pos_Total_Ratio','C_neg_Total_Ratio'
# ]

X = df_true[refined_features].copy()

# Calculate VIF
vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
print(vif_data.sort_values(by="VIF", ascending=False))

#베이스 모델
from sklearn.utils.class_weight import compute_sample_weight
# 2. 파생변수 생성
total_c = df_true["TOTAL_derived"] + 1e-5
df_true['C_0_Ratio'] = (df_true['C_0_derived'] / total_c) * 100
neg_cols = [f'C_neg{i}_derived' for i in range(1, 9)]
df_true['C_neg_Total_Ratio'] = (df_true[neg_cols].sum(axis=1) / total_c) * 100
pos_cols = [f'C_pos{i}_derived' for i in range(1, 7)]
df_true['C_pos_Total_Ratio'] = (df_true[pos_cols].sum(axis=1) / total_c) * 100

# 3. 모델에 사용할 독립변수 리스트
refined_features = [
    'Arlypon TT', 'Arlypon F',
    'Luviquat Excellence', 'Dehyquart CC6', 'Dehyquart CC7 Benz', 'Salcare Super 7',
    'C[N+](C)(C)C_derived', 'CS(=O)(=O)[O-]_derived', 'CC(=O)[O-]_derived', '[H]C(C)(OC)OC_derived',
    'C_0_Ratio', 'C_neg_Total_Ratio', 'C_pos_Total_Ratio'
]

# 결측치 제거
df_clean = df_true.dropna(subset=['Viscosity'] + refined_features).copy()

# 4. 데이터 전처리 (변수명 클리닝: LightGBM 특수문자 에러 해결)
X = df_clean[refined_features].copy()
# 특수문자를 언더바로 치환
X.columns = X.columns.str.replace(r'[\[\]<>,]', '_', regex=True)

y = LabelEncoder().fit_transform(df_clean['Viscosity'])

# 5. 학습/테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 6. 모델 정의 및 학습
models = {
    "Random Forest": RandomForestClassifier(class_weight='balanced', random_state=42),
    "LightGBM": LGBMClassifier(class_weight='balanced', random_state=42, verbose=-1),
    "XGBoost": XGBClassifier(random_state=42, eval_metric='mlogloss')
}

print("--- 모델 학습 및 평가 시작 ---")
for name, model in models.items():
    print(f"\n[{name} 모델]")

    if name == "XGBoost":
        weights = compute_sample_weight('balanced', y_train)
        model.fit(X_train, y_train, sample_weight=weights)
    else:
        model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    # 타겟 이름 확인을 위해 원본 데이터의 Viscosity 값 사용
    print(classification_report(y_test, y_pred))

print("\n[참고] 변수명이 특수문자 포함 시 모두 언더바(_)로 변환되었습니다.")
print("변환된 변수 목록:", X.columns.tolist())

mapping = dict(zip(le.classes_, le.transform(le.classes_)))

print("--- Viscosity 인코딩 매핑 정보 ---")
for label, encoded_value in mapping.items():
    print(f"'{label}' → {encoded_value}")

# 2. 추가 확인: 실제 학습 데이터셋의 분포 확인
# 각 클래스가 몇 개씩 데이터로 구성되었는지도 알 수 있습니다.
unique, counts = np.unique(y, return_counts=True)
print("\n--- 학습 데이터 내 클래스별 개수 ---")
for val, count in zip(unique, counts):
    label = le.inverse_transform([val])[0]
    print(f"'{label}' ({val}): {count}개")

# 이진 (HIGH + MEDIUM)(VERY-LOW + LOW)
total_c = df_true["TOTAL_derived"] + 1e-5
df_true['C_0_Ratio'] = (df_true['C_0_derived'] / total_c) * 100
neg_cols = [f'C_neg{i}_derived' for i in range(1, 9)]
df_true['C_neg_Total_Ratio'] = (df_true[neg_cols].sum(axis=1) / total_c) * 100
pos_cols = [f'C_pos{i}_derived' for i in range(1, 7)]
df_true['C_pos_Total_Ratio'] = (df_true[pos_cols].sum(axis=1) / total_c) * 100

def remap_viscosity(v):
    if v in ['LOW', 'VERY-LOW']:
        return 'VERY-LOW + LOW'
    elif v in ['MEDIUM', 'HIGH']:
        return 'HIGH + MEDIUM'
    return None

df_true['Viscosity_Binary'] = df_true['Viscosity'].apply(remap_viscosity)

# 3. 데이터 준비
refined_features = [
    'Arlypon TT', 'Arlypon F',
    'Luviquat Excellence', 'Dehyquart CC6', 'Dehyquart CC7 Benz', 'Salcare Super 7',
    'C[N+](C)(C)C_derived', 'CS(=O)(=O)[O-]_derived', 'CC(=O)[O-]_derived', '[H]C(C)(OC)OC_derived',
    'C_0_Ratio', 'C_neg_Total_Ratio', 'C_pos_Total_Ratio'
]

df_clean = df_true.dropna(subset=['Viscosity_Binary'] + refined_features).copy()
X = df_clean[refined_features].copy()
X.columns = X.columns.str.replace(r'[\[\]<>,]', '_', regex=True)

# 레이블 인코딩 (LOW_GROUP=0, HIGH_GROUP=1)
le = LabelEncoder()
y = le.fit_transform(df_clean['Viscosity_Binary'])

# 4. 학습/테스트 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 5. 모델 학습 및 평가
models = {
    "Random Forest": RandomForestClassifier(class_weight='balanced', random_state=42),
    "LightGBM": LGBMClassifier(class_weight='balanced', random_state=42, verbose=-1),
    "XGBoost": XGBClassifier(random_state=42, eval_metric='logloss')
}

print(f"--- 이진 분류 학습 시작 (매핑 확인: {dict(zip(le.classes_, le.transform(le.classes_)))}) ---")

for name, model in models.items():
    print(f"\n[{name} 모델]")

    if name == "XGBoost":
        weights = compute_sample_weight('balanced', y_train)
        model.fit(X_train, y_train, sample_weight=weights)
    else:
        model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    # 타겟 이름 확인을 위해 원본 데이터의 Viscosity 값 사용
    print(classification_report(y_test, y_pred, target_names=le.classes_))

# 1. 'LOW' 등급 데이터 제외
df_filtered = df_true[df_true['Viscosity'] != 'LOW'].copy()

# 2. 남은 등급을 다시 그룹화 (이진 분류 유지)
# VERY-LOW -> 'VERY-LOW'
# MEDIUM + HIGH -> 'HIGH + MEDIUM'
def remap_viscosity_filtered(v):
    if v == 'VERY-LOW':
        return 'VERY-LOW'
    elif v in ['MEDIUM', 'HIGH']:
        return 'HIGH + MEDIUM'
    return None

df_filtered['Viscosity_Binary'] = df_filtered['Viscosity'].apply(remap_viscosity_filtered)

# 3. 결측치 제거 및 데이터 준비
# (LOW를 제외하고 남은 등급이 None인 경우도 제거)
df_clean = df_filtered.dropna(subset=['Viscosity_Binary'] + refined_features).copy()

X = df_clean[refined_features].copy()
X.columns = X.columns.str.replace(r'[\[\]<>,]', '_', regex=True)

# 레이블 인코딩
le = LabelEncoder()
y = le.fit_transform(df_clean['Viscosity_Binary'])

# 4. 학습/테스트 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 5. 모델 학습 및 평가
models = {
    "Random Forest": RandomForestClassifier(class_weight='balanced', random_state=42),
    "LightGBM": LGBMClassifier(class_weight='balanced', random_state=42, verbose=-1),
    "XGBoost": XGBClassifier(random_state=42, eval_metric='logloss')
}

print(f"--- 이진 분류 학습 시작 (매핑 확인: {dict(zip(le.classes_, le.transform(le.classes_)))}) ---")

for name, model in models.items():
    print(f"\n[{name} 모델]")

    if name == "XGBoost":
        weights = compute_sample_weight('balanced', y_train)
        model.fit(X_train, y_train, sample_weight=weights)
    else:
        model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    # 타겟 이름 확인을 위해 원본 데이터의 Viscosity 값 사용
    print(classification_report(y_test, y_pred, target_names=le.classes_))

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.preprocessing import LabelEncoder

df_true = df[df["Turbidity_NTU"].notnull()].copy()


# 파생변수 (전체 대비 성분 비율)
target_features = ['C_0_derived','C_neg4_derived','C_pos2_derived']

for col in target_features:
    new_col_name = col.replace('_derived', '_Ratio')
    df_true[new_col_name] = df_true[col] / (df_true["TOTAL_derived"] + 1e-5)


refined_features = [
    'Arlypon TT',  'Arlypon F', # 점증제 2개
    'Luviquat Excellence', 'Dehyquart CC6', 'Dehyquart CC7 Benz', 'Salcare Super 7', # 폴리머 5개
    '[H]C(C)(OC)OC_derived', 'CC(=O)[O-]_derived', 'CS(=O)(=O)[O-]_derived', 'C[N+](C)(C)C_derived', # 작용기 4개
    'C_0_Ratio',     # 중성 탄소수 비율
    'C_neg4_Ratio',  # 음이온 탄소수 비율
    'C_pos2_Ratio'   # 양이온 탄소수 비율
]

X_refined = df_true[refined_features]
y = df_true["Viscosity"]

# 혹시 모를 결측치 처리
X_refined = X_refined.loc[y.notnull()]
y = y.dropna()

# 문자열 점도 등급 라벨 인코딩
le = LabelEncoder()
y_encoded = le.fit_transform(y)


# 4. 하이퍼파라미터 후보군 설정 (데이터 불균형 가중치 파라미터 포함)
param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [None, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "class_weight": [None, "balanced"],  # 불균형을 해결해 줄 핵심 튜닝 옵션
}

# 5. 교차 검증 및 그리드 서치 세팅
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1,
)

# 6. 최적의 파라미터 조합 탐색 시작
print(f"엄선된 {len(refined_features)}개 피처로 데이터 불균형을 고려한 최적 파라미터 탐색을 시작합니다...")
grid_search.fit(X_refined, y_encoded)

# 7. 결과 출력
print("\n=== 피처 수정 후 최적화 결과 ===")
print(f"최고 정확도(Best Score): {grid_search.best_score_:.4f}")
print(f"최적의 파라미터 조합: {grid_search.best_params_}")

# 8. 최종 최강 모델 추출
best_model = grid_search.best_estimator_

import numpy as np
import pandas as pd
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

# 1. 데이터 준비 (기존 코드와 동일)
df_true = df[df["Turbidity_NTU"].notnull()].copy()
target_features = ['C_0_derived','C_neg4_derived','C_pos2_derived']
for col in target_features:
    new_col_name = col.replace('_derived', '_Ratio')
    df_true[new_col_name] = df_true[col] / (df_true["TOTAL_derived"] + 1e-5)

refined_features = [
    'Arlypon TT',  'Arlypon F',
    'Luviquat Excellence', 'Dehyquart CC6', 'Dehyquart CC7 Benz', 'Salcare Super 7',
    '[H]C(C)(OC)OC_derived', 'CC(=O)[O-]_derived', 'CS(=O)(=O)[O-]_derived', 'C[N+](C)(C)C_derived',
    'C_0_Ratio', 'C_neg4_Ratio', 'C_pos2_Ratio'
]

X_refined = df_true[refined_features].copy()
# [중요] LightGBM을 위해 변수명 클리닝 (특수문자 -> 언더바)
X_refined.columns = X_refined.columns.str.replace(r'[\[\]<>,]', '_', regex=True)

y = df_true["Viscosity"]
X_refined = X_refined.loc[y.notnull()]
y = y.dropna()

le = LabelEncoder()
y_encoded = le.fit_transform(y)

# 2. 모델 설정 (GridSearchCV 실행)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# 모델별 파라미터 그리드 정의
models_params = {
    "LightGBM": {
        "model": LGBMClassifier(class_weight='balanced', random_state=42, verbose=-1),
        "params": {
            "n_estimators": [100, 200],
            "learning_rate": [0.01, 0.1],
            "max_depth": [3, 5, 10],
            "num_leaves": [20, 31, 50]
        }
    },
    "XGBoost": {
        "model": XGBClassifier(random_state=42, eval_metric='mlogloss'),
        "params": {
            "n_estimators": [100, 200],
            "learning_rate": [0.01, 0.1],
            "max_depth": [3, 5, 10],
            "subsample": [0.8, 1.0]
        }
    }
}

# 3. 최적 파라미터 탐색 수행
for name, mp in models_params.items():
    print(f"\n>>> {name} 최적 파라미터 탐색 시작...")
    grid_search = GridSearchCV(
        estimator=mp["model"],
        param_grid=mp["params"],
        cv=cv,
        scoring="accuracy",
        n_jobs=-1,
        verbose=1
    )
    grid_search.fit(X_refined, y_encoded)

    print(f"=== {name} 최적화 결과 ===")
    print(f"최고 정확도: {grid_search.best_score_:.4f}")
    print(f"최적 파라미터: {grid_search.best_params_}")

# 1. 'LOW' 등급 데이터 제외
df_filtered = df_true[df_true['Viscosity'] != 'LOW'].copy()

# 2. 남은 등급을 다시 그룹화 (이진 분류 유지)
# VERY-LOW -> 'VERY-LOW'
# MEDIUM + HIGH -> 'HIGH + MEDIUM'
def remap_viscosity_filtered(v):
    if v == 'VERY-LOW':
        return 'VERY-LOW'
    elif v in ['MEDIUM', 'HIGH']:
        return 'HIGH + MEDIUM'
    return None

df_filtered['Viscosity_Binary'] = df_filtered['Viscosity'].apply(remap_viscosity_filtered)

# 3. 결측치 제거 및 데이터 준비
# (LOW를 제외하고 남은 등급이 None인 경우도 제거)
df_clean = df_filtered.dropna(subset=['Viscosity_Binary'] + refined_features).copy()

X = df_clean[refined_features].copy()
X.columns = X.columns.str.replace(r'[\[\]<>,]', '_', regex=True)

# 레이블 인코딩
le = LabelEncoder()
y = le.fit_transform(df_clean['Viscosity_Binary'])

# 4. 학습/테스트 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 5. 모델 학습 및 평가
models = {
    "Random Forest": RandomForestClassifier(class_weight='balanced', max_depth=10, min_samples_split=10, n_estimators=100, random_state=42),
    "LightGBM": LGBMClassifier(learning_rate=0.1, max_depth=10, n_estimators=200, num_leaves=20, random_state=42, verbose=-1),
    "XGBoost": XGBClassifier(learning_rate=0.1, max_depth=10, n_estimators=100, subsample=0.8, random_state=42, eval_metric='logloss')
}

print(f"--- 이진 분류 학습 시작 (매핑 확인: {dict(zip(le.classes_, le.transform(le.classes_)))}) ---")

for name, model in models.items():
    print(f"\n[{name} 모델]")

    if name == "XGBoost":
        weights = compute_sample_weight('balanced', y_train)
        model.fit(X_train, y_train, sample_weight=weights)
    else:
        model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    # 타겟 이름 확인을 위해 원본 데이터의 Viscosity 값 사용
    print(classification_report(y_test, y_pred, target_names=le.classes_))