# -*- coding: utf-8 -*-
"""탁도_분석_최종.ipynb의 사본의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntAi4WNI7UrcF2kspoWZ2wgcfw6OGPV9

## 폰트설정
"""

# !apt-get install -y fonts-nanum
# !fc-cache -fv
# !rm ~/.cache/matplotlib -rf

# === 기본 라이브러리 ===
import os
import warnings
from contextlib import contextmanager
from time import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

# === 머신러닝 ===
import lightgbm as lgbm
from scipy import stats
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression,HuberRegressor
from scipy.stats import spearmanr,mannwhitneyu
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import (
    mean_squared_error, mean_absolute_error, r2_score,
    classification_report, confusion_matrix,
    accuracy_score, f1_score, roc_auc_score,
)

# === 시각화 한글/스타일 설정 ===
warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid')

# 2. 위에서 출력된 폰트 이름 중 하나를 여기에 정확히 적어주세요!
font_family = 'NanumBarunGothic'

# 3. 맷플롯립과 시본에 강제로 고정
plt.rc('font', family=font_family)
sns.set_theme(style='whitegrid', font=font_family)
plt.rcParams['axes.unicode_minus'] = False

print(f"🔥 {font_family} 폰트로 강제 고정 완료!")

"""## 드라이브 연결"""

# 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

# 2. 경로 설정: '9냥해' 폴더 안의 '데이터 셋' 폴더를 타겟으로 합니다.
CANDIDATE_DIRS = [
    '/content/drive/MyDrive/9냥해/1. 데이터 셋',
    '/content/drive/MyDrive/9냥해',
    './data',
    '.'
]
def find_csv(filename: str) -> str:
    for d in CANDIDATE_DIRS:
        p = os.path.join(d, filename)
        if os.path.exists(p):
            return p
    raise FileNotFoundError(f"'{filename}'을(를) 찾을 수 없습니다. '9냥해' 내 폴더명을 확인하세요.")
try:
    MAIN = find_csv('Combined_data.csv')
    combined = pd.read_csv(MAIN)

    print("\n[성공] 모든 데이터를 정상적으로 불러왔습니다!")

except FileNotFoundError as e:
    print(f"[오류] {e}")

"""## 탁도 EDA"""

# ── 안정성 기준 분리 ──────────────────────────────────
df_true  = df[df['Stability_Test'] == True].copy()   # 안정 샘플
df_false = df[df['Stability_Test'] == False].copy()  # 불안정 샘플
print(f'안정(df_true): {len(df_true)}개 | 불안정(df_false): {len(df_false)}개')

# ── 탁도 데이터 준비 ──────────────────────────────────
df_turb = df_true.copy()
df_turb['Turbidity_NTU'] = pd.to_numeric(df_turb['Turbidity_NTU'], errors='coerce')
df_turb = df_turb.dropna(subset=['Turbidity_NTU'])
print(f'탁도 데이터(df_turb): {len(df_turb)}개')

# ── 탄소 비율 파생변수 생성 ───────────────────────────
c_neg_cols = [c for c in df.columns if c.startswith('C_neg') and c.endswith('_derived')]
c_pos_cols = [c for c in df.columns if c.startswith('C_pos') and c.endswith('_derived')]

df_turb['C_0_Ratio']         = df_turb['C_0_derived'] / df_turb['TOTAL_derived'].replace(0, np.nan)
df_turb['C_neg_Total_Ratio'] = df_turb[c_neg_cols].sum(axis=1) / df_turb['TOTAL_derived'].replace(0, np.nan)
df_turb['C_pos_Total_Ratio'] = df_turb[c_pos_cols].sum(axis=1) / df_turb['TOTAL_derived'].replace(0, np.nan)
print('파생변수 생성 완료: C_0_Ratio, C_neg_Total_Ratio, C_pos_Total_Ratio')

# ── 이진분류 타겟 생성 ────────────────────────────────
df_turb['탁도_이진'] = df_turb['Turbidity_NTU'].apply(
    lambda x: '탁함(>100)' if x > 100 else '맑음(≤100)'
)
print(f"\n탁도 분포:\n{df_turb['탁도_이진'].value_counts()}")

# ── 13개 독립변수 설정 ────────────────────────────────
import re

features_13 = [
    'CC(=O)[O-]_derived',
    'C_neg_Total_Ratio',
    '[H]C(C)(OC)OC_derived',
    'C_pos_Total_Ratio',
    'C_0_Ratio',
    'Luviquat Excellence',
    'Arlypon F',
    'Salcare Super 7',
    'Arlypon TT',
    'Dehyquart CC7 Benz',
    'C[N+](C)(C)C_derived',
    'Dehyquart CC6',
    'CS(=O)(=O)[O-]_derived',
]

X_bin13       = df_turb[features_13].fillna(0)
X_bin13_clean = X_bin13.copy()
X_bin13_clean.columns = [re.sub(r'[^a-zA-Z0-9_]', '_', col) for col in X_bin13_clean.columns]

from sklearn.preprocessing import LabelEncoder
le           = LabelEncoder()
y_bin        = df_turb['탁도_이진']
y_bin_encoded = le.fit_transform(y_bin)

print(f'\n독립변수: {len(features_13)}개')
print(f'타겟 클래스: {le.classes_}')
print('\n데이터 준비 완료! ✓')

# ── 탁도 EDA ─────────────────────────────────────────
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ── 1. 탁도 분포 히스토그램 ───────────────────────────
fig, ax = plt.subplots(figsize=(8, 5))
ax.hist(df_turb['Turbidity_NTU'], bins=40,
        color='#4A7BA7', edgecolor='white', linewidth=0.5)
ax.axvline(x=df_turb['Turbidity_NTU'].median(),
           color='#2E75B6', linewidth=2, linestyle='--',
           label=f'중앙값: {df_turb["Turbidity_NTU"].median():.0f} NTU')
ax.axvline(x=df_turb['Turbidity_NTU'].mean(),
           color='#8EA9C1', linewidth=2, linestyle='-.',
           label=f'평균값: {df_turb["Turbidity_NTU"].mean():.0f} NTU')
ax.annotate('극단값 존재\n(최대 3,881 NTU)',
            xy=(3881, 1), xytext=(2800, 30),
            fontsize=10, color='#4A4A4A',
            arrowprops=dict(arrowstyle='->', color='#4A4A4A'))
ax.set_title('탁도(Turbidity_NTU) 분포', fontsize=13, weight='bold')
ax.set_xlabel('탁도 (NTU)')
ax.set_ylabel('샘플 수')
ax.legend(fontsize=10)
plt.tight_layout()
plt.savefig('탁도_히스토그램.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

# ── 2. 탁도 기초 통계 ────────────────────────────────
print('=== 탁도 기초 통계 ===')
print(df_turb['Turbidity_NTU'].describe().round(1))
print(f'\n300 NTU 이상: {(df_turb["Turbidity_NTU"] > 300).sum()}개')
print(f'1000 NTU 이상: {(df_turb["Turbidity_NTU"] > 1000).sum()}개')

# ── 3. 이진분류 분포 + 비율 ───────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
counts = df_turb['탁도_이진'].value_counts()
colors_dist = ['#AED6F1', '#4A7BA7']

bars = axes[0].bar(['맑음 (≤100 NTU)', '탁함 (>100 NTU)'],
                   counts.values, color=colors_dist,
                   edgecolor='gray', width=0.4)
for bar, val in zip(bars, counts.values):
    axes[0].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 1,
                 f'{val}개\n({val/len(df_turb)*100:.1f}%)',
                 ha='center', fontsize=11, weight='bold')
axes[0].set_title('이진분류 기준 탁도 분포', fontsize=13, weight='bold')
axes[0].set_ylabel('샘플 수')
axes[0].set_ylim(0, 280)

axes[1].pie(counts.values,
            labels=['맑음 (≤100 NTU)', '탁함 (>100 NTU)'],
            colors=colors_dist, autopct='%1.1f%%', startangle=90)
axes[1].set_title('맑음 / 탁함 비율', fontsize=13, weight='bold')
plt.tight_layout()
plt.savefig('이진분류_분포.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

"""## 탁도 ML"""

# ── 베이스라인 모델 ───────────────────────────────────
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# ── 6개 모델 비교 (SMOTE vs 클래스 가중치) ───────────
models = {
    'Random Forest + SMOTE': Pipeline([
        ('smote', SMOTE(random_state=42)),
        ('clf', RandomForestClassifier(n_estimators=100, random_state=42))
    ]),
    'LightGBM + SMOTE': Pipeline([
        ('smote', SMOTE(random_state=42)),
        ('clf', LGBMClassifier(n_estimators=100, random_state=42, verbose=-1))
    ]),
    'XGBoost + SMOTE': Pipeline([
        ('smote', SMOTE(random_state=42)),
        ('clf', XGBClassifier(n_estimators=100, random_state=42, verbosity=0))
    ]),
    'Random Forest + 클래스 가중치': RandomForestClassifier(
        n_estimators=100, class_weight='balanced', random_state=42),
    'LightGBM + 클래스 가중치': LGBMClassifier(
        n_estimators=100, class_weight='balanced', random_state=42, verbose=-1),
    'XGBoost + 클래스 가중치': XGBClassifier(
        n_estimators=100, scale_pos_weight=237/57, random_state=42, verbosity=0),
}

print('=== 6개 모델 비교 (5-Fold 교차검증) ===\n')
results = []
for name, model in models.items():
    scores = cross_val_score(model, X_bin13_clean, y_bin_encoded,
                             cv=skf, scoring='f1_weighted')
    print(f'{name}')
    print(f'  F1: {scores.mean():.3f} (±{scores.std():.3f})\n')
    results.append({'모델': name, 'F1': scores.mean(), 'std': scores.std()})

best = max(results, key=lambda x: x['F1'])
print(f'>>> 최고 성능: {best["모델"]} (F1 {best["F1"]:.3f})')
print('>>> 최종 채택: LightGBM + 클래스 가중치')
print('    이유: F1 차이 0.001, 표준편차 가장 낮음(±0.037)')

# ── 6개 모델 비교 표 ──────────────────────────────────
fig, ax = plt.subplots(figsize=(13, 4))
ax.axis('off')
table_data = [
    ['Random Forest + SMOTE',        f'{results[0]["F1"]:.3f}', f'±{results[0]["std"]:.3f}', 'SMOTE'],
    ['LightGBM + SMOTE',             f'{results[1]["F1"]:.3f}', f'±{results[1]["std"]:.3f}', 'SMOTE'],
    ['XGBoost + SMOTE',              f'{results[2]["F1"]:.3f}', f'±{results[2]["std"]:.3f}', 'SMOTE'],
    ['Random Forest + 클래스 가중치',f'{results[3]["F1"]:.3f}', f'±{results[3]["std"]:.3f}', '클래스 가중치'],
    ['LightGBM + 클래스 가중치',     f'{results[4]["F1"]:.3f}', f'±{results[4]["std"]:.3f}', '클래스 가중치'],
    ['XGBoost + 클래스 가중치',      f'{results[5]["F1"]:.3f}', f'±{results[5]["std"]:.3f}', '클래스 가중치'],
]
col_labels = ['모델', 'F1 Score', '표준편차', '불균형 처리 방법']
table = ax.table(cellText=table_data, colLabels=col_labels,
                 cellLoc='center', loc='center')
table.auto_set_font_size(False)
table.set_fontsize(11)
table.scale(1, 2.2)
for col in range(4):
    table[0, col].set_facecolor('#5D6D7E')
    table[0, col].set_text_props(color='white', weight='bold')
for row in range(1, 4):
    for col in range(4):
        table[row, col].set_facecolor('#D6DCE4')
for row in range(4, 7):
    for col in range(4):
        table[row, col].set_facecolor('#E8E8E8')
for col in range(4):
    table[5, col].set_text_props(weight='bold')
    table[5, col].set_edgecolor('#E74C3C')
    table[5, col].set_linewidth(3)
import matplotlib.patches as mpatches
smote_patch = mpatches.Patch(color='#D6DCE4', label='SMOTE')
cw_patch    = mpatches.Patch(color='#E8E8E8', label='클래스 가중치')
ax.legend(handles=[smote_patch, cw_patch], loc='lower right',
          bbox_to_anchor=(1, -0.05), fontsize=10)
ax.set_title('모델 성능 비교 (이진분류, 5-Fold 교차검증)',
             fontsize=13, weight='bold', pad=20)
plt.tight_layout()
plt.savefig('6개모델_비교표.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

# ── 필요 패키지 설치 (코랩 환경) ─────────────────────
!pip install optuna lightgbm xgboost imbalanced-learn -q

# ── 하이퍼파라미터 튜닝 (Optuna) ─────────────────────
import optuna
import time
from sklearn.model_selection import cross_val_score, StratifiedKFold

optuna.logging.set_verbosity(optuna.logging.WARNING)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# ── GridSearchCV ──────────────────────────────────────
from sklearn.model_selection import GridSearchCV

print('① GridSearchCV 시작...')
start = time.time()
param_grid = {
    'n_estimators':  [100, 200, 300],
    'learning_rate': [0.05, 0.1, 0.2],
    'max_depth':     [3, 5, 7],
}
grid = GridSearchCV(
    LGBMClassifier(class_weight='balanced', random_state=42, verbose=-1),
    param_grid, cv=skf, scoring='f1_weighted', n_jobs=-1)
grid.fit(X_bin13_clean, y_bin_encoded)
print(f'  F1: {grid.best_score_:.3f} | 시간: {time.time()-start:.1f}초')

# ── RandomizedSearchCV ────────────────────────────────
from sklearn.model_selection import RandomizedSearchCV

print('\n② RandomizedSearchCV 시작...')
start = time.time()
param_dist = {
    'n_estimators':  [50, 100, 200, 300, 500],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'max_depth':     [3, 5, 7, 10, -1],
    'num_leaves':    [15, 31, 50, 63, 100],
}
random = RandomizedSearchCV(
    LGBMClassifier(class_weight='balanced', random_state=42, verbose=-1),
    param_dist, n_iter=50, cv=skf, scoring='f1_weighted',
    random_state=42, n_jobs=-1)
random.fit(X_bin13_clean, y_bin_encoded)
print(f'  F1: {random.best_score_:.3f} | 시간: {time.time()-start:.1f}초')

# ── Optuna (최종 선택) ────────────────────────────────
print('\n③ Optuna 시작...')
start = time.time()

def objective(trial):
    params = {
        'n_estimators':  trial.suggest_int('n_estimators', 50, 500),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'max_depth':     trial.suggest_int('max_depth', 3, 10),
        'num_leaves':    trial.suggest_int('num_leaves', 15, 100),
        'class_weight':  'balanced',
        'random_state':  42,
        'verbose':       -1
    }
    model = LGBMClassifier(**params)
    scores = cross_val_score(model, X_bin13_clean, y_bin_encoded,
                             cv=skf, scoring='f1_weighted')
    return scores.mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)
optuna_time = time.time() - start
print(f'  F1: {study.best_value:.3f} | 시간: {optuna_time:.1f}초')

# ── 튜닝 결과 비교 ────────────────────────────────────
print('\n=== 하이퍼파라미터 튜닝 결과 비교 ===')
print(f'베이스라인:        F1 0.789')
print(f'GridSearch:        F1 {grid.best_score_:.3f}')
print(f'RandomizedSearch:  F1 {random.best_score_:.3f}')
print(f'Optuna (최종선택): F1 {study.best_value:.3f}')
print(f'\nOptuna 최적 파라미터: {study.best_params}')

# ── 튜닝 비교 그래프 ──────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 5))
names  = ['베이스라인', 'GridSearchCV', 'RandomizedSearchCV', 'Optuna\n(최종 선택)']
values = [0.789, grid.best_score_, random.best_score_, study.best_value]
colors = ['#D5D8DC', '#AED6F1', '#B8D4E8', '#7FB3D3']

bars = ax.bar(names, values, color=colors, edgecolor='#8899AA', width=0.45)
for bar, f in zip(bars, values):
    ax.text(bar.get_x() + bar.get_width()/2, 0.786,
            f'F1: {f:.3f}', ha='center', va='bottom',
            fontsize=11, weight='bold', color='#333333')
bars[3].set_edgecolor('#E74C3C')
bars[3].set_linewidth(3)
ax.text(bars[3].get_x() + bars[3].get_width()/2, values[3]-0.0002,
        '★ 최종 선택', ha='center', va='top',
        fontsize=10, color='#E74C3C', weight='bold')
ax.axhline(y=0.789, color='#E74C3C', linewidth=1.5,
           linestyle='--', label='베이스라인 (F1 0.789)')
ax.set_title('하이퍼파라미터 튜닝 방법별 성능 비교\n(LightGBM + 클래스 가중치)',
             fontsize=13, weight='bold')
ax.set_ylabel('F1 Score')
ax.set_ylim(0.784, values[3]+0.004)
ax.legend(fontsize=10)
plt.tight_layout()
plt.savefig('튜닝비교.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

# ── Optuna 파라미터 표 ────────────────────────────────
fig, ax = plt.subplots(figsize=(13, 3.5))
ax.axis('off')
param_data = [
    ['n_estimators',  '50 ~ 500',       str(study.best_params['n_estimators']),
     '생성할 결정나무 수 (많을수록 안정적)'],
    ['learning_rate', '0.01 ~ 0.3',     f"{study.best_params['learning_rate']:.3f}",
     '매 단계 학습 크기 (작을수록 정밀, 클수록 과적합 위험)'],
    ['max_depth',     '3 ~ 10',         str(study.best_params['max_depth']),
     '결정나무 최대 깊이 — 질문 횟수 (깊을수록 세밀)'],
    ['num_leaves',    '15 ~ 100',       str(study.best_params['num_leaves']),
     '결정나무 끝 가지 수 (많을수록 복잡한 패턴 학습)'],
    ['class_weight',  'balanced (고정)', 'balanced',
     '탁함 샘플에 자동 가중치 부여하여 불균형 해소'],
]
col_labels = ['파라미터', '탐색 범위', '최적값', '설명']
table = ax.table(cellText=param_data, colLabels=col_labels,
                 cellLoc='center', loc='center',
                 colWidths=[0.2, 0.18, 0.12, 0.50])
table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 2.0)
for col in range(4):
    table[0, col].set_facecolor('#4A4A4A')
    table[0, col].set_text_props(color='white', weight='bold')
for row in range(1, 6):
    color = '#D6DCE4' if row % 2 == 0 else '#EAECEE'
    for col in range(4):
        table[row, col].set_facecolor(color)
for row in range(1, 6):
    table[row, 2].set_text_props(weight='bold', color='#2E75B6')
ax.set_title('Optuna 하이퍼파라미터 탐색 결과\n(LightGBM + 클래스 가중치, 50 trials)',
             fontsize=13, weight='bold', pad=15)
plt.tight_layout()
plt.savefig('파라미터표.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

# ── 최종 모델 구성 (Optuna 최적 파라미터 적용) ────────
from sklearn.model_selection import cross_val_predict, StratifiedKFold
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

final_model = LGBMClassifier(
    n_estimators  = study.best_params['n_estimators'],
    learning_rate = study.best_params['learning_rate'],
    max_depth     = study.best_params['max_depth'],
    num_leaves    = study.best_params['num_leaves'],
    class_weight  = 'balanced',
    random_state  = 42,
    verbose       = -1
)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# ── 교차검증 기반 예측 ────────────────────────────────
scores = cross_val_score(final_model, X_bin13_clean, y_bin_encoded,
                         cv=skf, scoring='f1_weighted')
print(f'=== 최종 모델 성능 ===')
print(f'F1 Score: {scores.mean():.3f} (±{scores.std():.3f})')

y_pred_final = cross_val_predict(final_model, X_bin13_clean,
                                  y_bin_encoded, cv=skf)

# ── 혼동행렬 시각화 ───────────────────────────────────
label_names    = ['맑음 (≤100 NTU)', '탁함 (>100 NTU)']
y_actual_labels = ['맑음 (≤100 NTU)' if v == 0 else '탁함 (>100 NTU)' for v in y_bin_encoded]
y_pred_labels   = ['맑음 (≤100 NTU)' if v == 0 else '탁함 (>100 NTU)' for v in y_pred_final]

fig, ax = plt.subplots(figsize=(6, 5))
cm = confusion_matrix(y_actual_labels, y_pred_labels, labels=label_names)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_names, yticklabels=label_names,
            ax=ax, annot_kws={'size': 14, 'weight': 'bold'})
ax.set_title('최종 모델 혼동행렬\n(LightGBM + Optuna + Class Weight)',
             fontsize=13, weight='bold')
ax.set_xlabel('예측값 (Predicted)')
ax.set_ylabel('실제값 (Actual)')
ax.text(0.5, -0.18,
        f'✓ 정답: TN {cm[0][0]} + TP {cm[1][1]} = {cm[0][0]+cm[1][1]}개 ({(cm[0][0]+cm[1][1])/len(y_bin_encoded)*100:.1f}%)',
        ha='center', transform=ax.transAxes, fontsize=11,
        color='#2E75B6', weight='bold')
ax.text(0.5, -0.26,
        f'✗ 오답: FP {cm[0][1]} + FN {cm[1][0]} = {cm[0][1]+cm[1][0]}개 ({(cm[0][1]+cm[1][0])/len(y_bin_encoded)*100:.1f}%)',
        ha='center', transform=ax.transAxes, fontsize=11,
        color='#8EA9C1', weight='bold')
plt.tight_layout()
plt.savefig('최종모델_혼동행렬.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

# ── 상세 분류 결과 ────────────────────────────────────
print('\n=== 상세 분류 결과 ===')
print(classification_report(y_actual_labels, y_pred_labels))

# ── 색상 설정 ─────────────────────────────────────────
P_BLUE  = '#AED6F1'
P_GREEN = '#A9DFBF'
P_PINK  = '#F1948A'
P_GRAY  = '#D5D8DC'

# ── 변수 중요도 (Feature Importance) ─────────────────
import matplotlib.patches as mpatches

final_model.fit(X_bin13_clean, y_bin_encoded)
importance_final = pd.Series(final_model.feature_importances_,
                             index=X_bin13_clean.columns).sort_values()

colors_imp = [P_PINK if i >= len(importance_final)-3 else P_BLUE
              for i in range(len(importance_final))]


fig, ax = plt.subplots(figsize=(10, 6))
importance_final.plot(kind='barh', ax=ax, color=colors_imp, edgecolor='gray')
ax.set_title('변수 중요도 — 최종 모델\n(LightGBM + Optuna + Class Weight)',
             fontsize=13, weight='bold')
ax.set_xlabel('중요도')
top_patch   = mpatches.Patch(color=P_PINK, label='상위 3개 변수')
other_patch = mpatches.Patch(color=P_BLUE, label='나머지 변수')
ax.legend(handles=[top_patch, other_patch], fontsize=10)
plt.tight_layout()
plt.savefig('최종모델_변수중요도.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()


# ── SHAP 분석 ─────────────────────────────────────────
import shap

explainer   = shap.TreeExplainer(final_model)
shap_values = explainer.shap_values(X_bin13_clean)

if isinstance(shap_values, list):
    sv = shap_values[1]
else:
    sv = shap_values

# 변수명 한글 매핑
name_map = {
    'CC__O__O___derived':    'CC__O__O___derived (카르복실레이트)',
    'C_neg_Total_Ratio':     'C_neg_Total_Ratio (음전하 탄소 비율)',
    '_H_C_C__OC_OC_derived': '_H_C_C__OC_OC_derived (바이온)',
    'C_pos_Total_Ratio':     'C_pos_Total_Ratio (양전하 탄소 비율)',
    'C_0_Ratio':             'C_0_Ratio (중성 탄소 비율)',
    'Luviquat_Excellence':   'Luviquat_Excellence (양이온 폴리머)',
    'Arlypon_F':             'Arlypon_F (증점제)',
    'Salcare_Super_7':       'Salcare_Super_7 (양이온 폴리머)',
    'Arlypon_TT':            'Arlypon_TT (증점제)',
    'Dehyquart_CC7_Benz':    'Dehyquart_CC7_Benz (양이온 폴리머)',
    'C_N___C__C_C_derived':  'C_N___C__C_C_derived (양이온기)',
    'Dehyquart_CC6':         'Dehyquart_CC6 (양이온 폴리머)',
    'CS__O___O__O___derived':'CS__O___O__O___derived (설포네이트)',
}
X_shap = X_bin13_clean.rename(columns=name_map)

# ── SHAP Summary Plot ─────────────────────────────────
plt.figure(figsize=(12, 7))
shap.summary_plot(sv, X_shap, show=False)
plt.title('SHAP Summary Plot — 탁함 예측 변수 영향\n(LightGBM + Optuna + Class Weight)',
          fontsize=13, weight='bold')
plt.xlabel('SHAP 값 (탁함 예측 기여도)')
cb = plt.gcf().axes[-1]
cb.set_ylabel('특성값', fontsize=10)
plt.tight_layout()
plt.savefig('SHAP_summary.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

# ── SHAP Bar Plot ─────────────────────────────────────
fig, ax = plt.subplots(figsize=(12, 6))
shap.summary_plot(sv, X_shap, plot_type='bar', show=False, color='#85C1E9')
ax = plt.gca()
ax.set_xlabel('평균 |SHAP 값| (변수 중요도)', fontsize=11)
plt.title('SHAP 변수 중요도 (평균 절댓값)\n(LightGBM + Optuna + Class Weight)',
          fontsize=13, weight='bold')
plt.tight_layout()
plt.savefig('SHAP_bar.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()


# ── SHAP Waterfall (TP / FN) ──────────────────────────
from sklearn.model_selection import cross_val_predict

y_pred_cv   = cross_val_predict(final_model, X_bin13_clean, y_bin_encoded, cv=skf)
tp_indices  = [i for i in range(len(y_bin_encoded)) if y_bin_encoded[i]==1 and y_pred_cv[i]==1]
fn_indices  = [i for i in range(len(y_bin_encoded)) if y_bin_encoded[i]==1 and y_pred_cv[i]==0]

explanation = shap.Explanation(
    values      = sv,
    base_values = explainer.expected_value[1] if isinstance(explainer.expected_value, list)
                  else explainer.expected_value,
    data        = X_shap.values,
    feature_names = X_shap.columns.tolist()
)

# TP Waterfall
fig = plt.figure(figsize=(12, 9))
plt.subplots_adjust(top=0.76, bottom=0.08)
shap.waterfall_plot(explanation[tp_indices[0]], show=False)
fig.text(0.5, 0.97, 'SHAP Waterfall Plot', ha='center', fontsize=13, weight='bold')
fig.text(0.5, 0.93, 'TP 샘플  —  실제 탁함 → 탁함으로 올바르게 예측',
         ha='center', fontsize=10, weight='bold', color='#27AE60')
fig.text(0.5, 0.89, '← 맑음 방향으로 기여                                    탁함 방향으로 기여 →',
         ha='center', fontsize=9, color='#2980B9', weight='bold')
plt.savefig('SHAP_waterfall_TP.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

# FN Waterfall
fig = plt.figure(figsize=(12, 9))
plt.subplots_adjust(top=0.76, bottom=0.08)
shap.waterfall_plot(explanation[fn_indices[0]], show=False)
fig.text(0.5, 0.97, 'SHAP Waterfall Plot', ha='center', fontsize=13, weight='bold')
fig.text(0.5, 0.93, 'FN 샘플  —  실제 탁함 → 맑음으로 잘못 예측',
         ha='center', fontsize=10, weight='bold', color='#E74C3C')
fig.text(0.5, 0.89, '← 맑음 방향으로 기여                                    탁함 방향으로 기여 →',
         ha='center', fontsize=9, color='#2980B9', weight='bold')
plt.savefig('SHAP_waterfall_FN.png', transparent=True, bbox_inches='tight', dpi=300)
plt.show()

print('✓ 모든 분석 완료!')